// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPvdVCTYzKTbVcCBeg-jZozCAEpBz5Ahc',
    appId: '1:66561420209:web:42264b37ec3f371b3beb90',
    messagingSenderId: '66561420209',
    projectId: 'golden-gym-kh',
    authDomain: 'golden-gym-kh.firebaseapp.com',
    storageBucket: 'golden-gym-kh.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfiqxCFde6yf4dE5CT8b-PaPG0anrxhvM',
    appId: '1:66561420209:android:dfb725b385f1a8ae3beb90',
    messagingSenderId: '66561420209',
    projectId: 'golden-gym-kh',
    storageBucket: 'golden-gym-kh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbmSi4PcDx9fXTfn8znTQhi6OC8hlHqvU',
    appId: '1:66561420209:ios:b1515c8e9c5681263beb90',
    messagingSenderId: '66561420209',
    projectId: 'golden-gym-kh',
    storageBucket: 'golden-gym-kh.firebasestorage.app',
    iosBundleId: 'com.shosha.gymManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbmSi4PcDx9fXTfn8znTQhi6OC8hlHqvU',
    appId: '1:66561420209:ios:b1515c8e9c5681263beb90',
    messagingSenderId: '66561420209',
    projectId: 'golden-gym-kh',
    storageBucket: 'golden-gym-kh.firebasestorage.app',
    iosBundleId: 'com.shosha.gymManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPvdVCTYzKTbVcCBeg-jZozCAEpBz5Ahc',
    appId: '1:66561420209:web:7d8fd727944a65e13beb90',
    messagingSenderId: '66561420209',
    projectId: 'golden-gym-kh',
    authDomain: 'golden-gym-kh.firebaseapp.com',
    storageBucket: 'golden-gym-kh.firebasestorage.app',
  );
}
